### ISSUE TITLE
start the repo with a skeleton 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api-documentation#1]
only the needed files 

inspirtion from here 

https://github.com/laminas-api-tools/documentation

**Comment by alexmerlin** [comment]
Initial files from `main` branch have been backed up into branch https://github.com/dotkernel/api-documentation/tree/initial
`main` branch overwritten with new documentation files moved from [dotkernel/api](https://github.com/dotkernel/api) after https://github.com/dotkernel/api/pull/255.
