### ISSUE TITLE
add 3 new pages to documentation: flow schemes

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api-documentation#11]
https://www.dotkernel.org/page/flowLibraries
https://www.dotkernel.org/page/flowMiddlewares
https://www.dotkernel.org/page/flowLibrariesEmail

**Comment by bidi47** [comment]
added smaller versions of the files here https://github.com/dotkernel/dotkernel.github.io/tree/main/img/api
dotkernel-library-flow-75.jpg
dotkernel-library-flow-email-75.jpg
dotkernel-middleware-flow-75.jpg

**Comment by bidi47** [comment]
this thread can be closed
new changes were requested here
https://github.com/dotkernel/api-documentation/issues/13
