### ISSUE TITLE
add pages to core features

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api-documentation#23]
- [x] Authorisation
- [x] Authentication
- [x] CORS - see [this article](https://www.dotkernel.com/how-to/mezzio-cors-implementation-in-dotkernel/)
- [x] `Create admin account` command - see [this document](https://github.com/dotkernel/api/blob/4.0/documentation/command/admin-create.md)
- [x] `Generate database migrations` command - see [this document](https://github.com/dotkernel/api/blob/4.0/documentation/command/migrations-diff.md)
- [x] `Display available endpoints` command - see [this document](https://github.com/dotkernel/api/blob/4.0/documentation/command/route-list.md)
- [x] `Generate tokens` command - see [this document](https://github.com/dotkernel/api/blob/4.0/documentation/command/token-generate.md)

**Comment by arhimede** [comment]
@bogdan , those 4 pages 
          - "Create admin account": v4/commands/create-admin-account.md
          - "Generate database migrations": v4/commands/generate-database-migrations.md
          - "Display available endpoints": v4/commands/display-available-endpoints.md
          - "Generate tokens": v4/commands/generate-tokens.md

**Comment by alexmerlin** [comment]
Fixed in #25, #27 and #31
