### ISSUE TITLE
Latest Dotkernel deployment to Nginx

### ISSUE THREAD

**Issue by aris-setiawan** [dotkernel/api-documentation#60]
Hi folks,

I'm looking at Dotkernel v5 deployment steps to the Nginx server but I only found this link that still uses the old Dotkernel:
https://www.dotkernel.com/dotkernel/dotkernel-on-nginx/
Are there any production-grade deployment docs for the latest Dotkernel to Nginx?

Many thanks,
Aris

**Comment by arhimede** [comment]
There are no specific instructions for Nginx versus Apache installation.

The only difference is that on Nginx there is no .htaccess file and the setup of the server need to be done 
more or less following this instructions: https://www.dotkernel.com/dotkernel/dotkernel-on-nginx/

In the near future , we will add specific instructions for nginx setup.

**Comment by aris-setiawan** [comment]
Thank you for the fast response.
