### ISSUE TITLE
Tutorial on how to also retrieve resource by a unique property, other than UUID

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/api-documentation#61]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

https://github.com/dotkernel/api/issues/328

**Comment by arhimede** [comment]
solve in #62

**Comment by matthewpallotta** [comment]
I had one issue with the documentation. Config needed to be added to the new Handler Inject and __construct.
`#[Inject(
        HalResponseFactory::class,
        ResourceGenerator::class,
        UserServiceInterface::class,
        "config",
    )]
    public function __construct(
        protected HalResponseFactory $responseFactory,
        protected ResourceGenerator $resourceGenerator,
        protected UserServiceInterface $userService,
        protected array $config,
    ) {
    }`

**Comment by alexmerlin** [comment]
@matthewpallotta Since you created your clone of Dotkernel API, we refactored the handlers multiple times.
If you want to implement them in your project, here are the relevant PRs:

* https://github.com/dotkernel/api/pull/315
* https://github.com/dotkernel/api/pull/338

The tutorial was made for the latest version of Dotkernel API, using the refactored structure, that's why it does not mention the need for `$config` to be injected in the handler's constructor.
