### ISSUE TITLE
Explain why error reporting needs to be token-protected

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/api-documentation#64]
See [this discussion](https://github.com/dotkernel/api/discussions/335) on why this needs further clarifications.

[This comment](https://github.com/dotkernel/api/discussions/335#discussioncomment-11082376) can be used as source for explaining the necessity of token protection for the error reporting endpoint.

**Comment by bidi47** [comment]
updated in https://github.com/dotkernel/api-documentation/pull/67
i added an extra line in the intro
